### PR TITLE
Add install ghc step

### PR DESCRIPTION
**Pull request by enzief**
As a completely new `nix`/`cabal` user, it took me a day to figure it out.

### CODE REVIEW

**Comment by enzief** [comment]
Thanks for the clarification. I'm not aware of `--packages ghc` either.
I copy-paste-d  every step explained in project0 but got stuck because `cabal` needs `ghc` which is not there. Perhaps `--packages ghc` can be added to all the `nix-shell ...` in the tutorial?

**Comment by enzief** [comment]
@Gabriel439 well it doesn't work for me. Without installing `ghc` I don't know how to follow the tutorial in Project0
```bash
$ nix-shell --packages ghc --attr env release0.nix                                                                                                            error: attribute 'env' in selection path 'env' not found
```

**Comment by Gabriel439** [comment]
@enzief: You shouldn't need `--packages ghc` in this case.  What you tried the first time was the correct set of steps if the `nix-shell` succeeded:

```
$ nix-shell --attr env release0.nix
$ cabal configure
```

What I think happened in your case is that the first `nix-shell` command failed and so as a result the `cabal configure` command was not run inside of a `nix-shell`.  To be extra sure, run this:

```haskell
$ nix-shell --attr env release0.nix --run 'cabal configure'
```

If that still doesn't work, then run this:

```haskell
$ nix-shell --attr env release0.nix --run 'ghc --version
```

**Comment by enzief** [comment]
Just figured out that it didn't work for me because I used `Windows Subsystem for Linux`. When I followed the tutorial in a proper OS (MacOS) it worked perfectly fine.
@Gabriel439 thanks for the help! Can I close this?

**Comment by Gabriel439** [comment]
You're welcome!  Sure, I'll go ahead and close this

**Pull request closed without merging**
